### ISSUE TITLE
RFC: Change indentation?

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#15]
I use tabs in almost all of my projects, but the ruby world has more or less settled on two-space indentation.

Would changing `ruby-macho` to use two-space indentation be appreciated? Currently, whenever I update the vendored version in Homebrew, I run a little script to change it. I could just run that script in the repo and have it done in a single commit.

(Feel free to shoot this down if it's pointless - I just remembering seeing the indentation as a nit when originally getting ruby-macho merged in).

cc: @mikemcquaid @UniqMartin

**Comment by mikemcquaid** [comment]
> Would changing ruby-macho to use two-space indentation be appreciated? Currently, whenever I update the vendored version in Homebrew, I run a little script to change it. I could just run that script in the repo and have it done in a single commit.

Yeh, sounds like a good idea :+1:

**Comment by UniqMartin** [comment]
I'm also in favor of changing to two-space indentation. Too bad this is going to make the existing repository history almost useless, but better now than later.

**Comment by xu-cheng** [comment]
I suggest to run all the ruby code against `brew style --fix` to improve the code style.

**Comment by woodruffw** [comment]
@UniqMartin Yeah, this was my primary concern.

@xu-cheng I'll look into that as well, thanks.

I'll make this change tonight.
