### ISSUE TITLE
Serialization of artificially created load commands

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#36]
One eventual goal of `ruby-macho` is to be able to *add* new load commands to a Mach-O file, not just modify the already present ones.

We want to make this sort of operation as painless as possible, so it might make sense to create a system where load commands and other structures can be constructed manually and serialized into binary strings. For example:

```ruby
lc = VersionMinCommand.serialize(version, sdk) # => "\x24\x08..."
macho.add_command(lc) # or maybe 'add_lc'?
```

I'm open to other structure/layout ideas, that one's just a rough sketch.

cc @UniqMartin

**Comment by UniqMartin** [comment]
I think we need to talk a bit more about the interface that would be used to create those load commands that are not yet attached to a `MachOView` (or an underlying Mach-O file), but generally I think this is the right way to move forward. We will definitely need it to create new `LC_RPATH` load commands to be able to implement an equivalent of `install_name_tool -add_rpath` and as I elaborated in https://github.com/Homebrew/ruby-macho/pull/35#issuecomment-229658170 this would also help to simplify changing existing load commands.

I think the structure should be roughly as follows:

1. Instantiate a load command, e.g. `RpathCommand` from a string. At this point it doesn't know anything about endianness or possible padding requirements.
2. Hand over this “abstract” load command to `MachOFile#add_command` that would provide the necessary information about endianness and whether the file is 32/64-bit, asking the load command to serialize itself according to those parameters. It would further check if there's enough available space for the new load command and append it (effectively replace a chunk of zero bytes).
3. This design would also allow to create only one load command instance and then serialize it into multiple `MachOFile` instances, something that would be convenient when modifying fat binaries.

**Comment by woodruffw** [comment]
> I think we need to talk a bit more about the interface that would be used to create those load commands that are not yet attached to a MachOView (or an underlying Mach-O file)

One possible approach to this is a mix-in that exposes another initialization pathway. Since the only load commands we can add/remove cleanly are the ones that don't make (extensive) references to other locations in a binary, perhaps `IsolatedCommandExtension.new_isolated` or something to that effect?

**Comment by UniqMartin** [comment]
That's a good point that this only makes sense for a limited number of load commands! I agree that constructing the ones that make references to other parts of the Mach-O binary, most prominently the `__LINKEDIT` segment, doesn't make much sense.

What would be offered by the `IsolatedCommandExtension` aside from the new “constructor”? I wonder if we can re-design the existing code such that a free-floating (not yet attached to a particular Mach-O file and no fixed endianness and bit width) load command can be constructed via, e.g., `RpathCommand.new(path)`, but this sounds like too much work and for little gain plus we'd have to rethink how `new_from_bin` works.

How about we make that `RpathCommand.create(path)`? Other load commands, like `DylibCommand` would be less straightforward, as they require four arguments and one would have to additionally specify the exact load command as the same structure is reused for `LC_ID_DYLIB`, `LC_LOAD_DYLIB`, and a few others.

Just thinking aloud about some possible approaches. To be honest I don't have an idea yet that satisfies me truly. But maybe you can come up with something. Maybe you can just try some different approaches and see how that goes? The only commands we really need to implement this for are `RpathCommand` and `DylibCommand`, so the amount of refactoring if we later come up with a better idea should be bearable.

**Comment by woodruffw** [comment]
> I wonder if we can re-design the existing code such that a free-floating (not yet attached to a particular Mach-O file and no fixed endianness and bit width) load command can be constructed via, e.g., RpathCommand.new(path), but this sounds like too much work and for little gain plus we'd have to rethink how new_from_bin works.

Yeah, I'm not sure that this particular approach is possible without adding a fair bit of complexity to the way we currently initialize load commands. I'd like to keep the number of constructors for a given class to a minimum, but it feels like we'll be paying a high price in both internal and public API complexity for it.

> How about we make that RpathCommand.create(path)?

I think this would be reasonable. I hadn't thought of that issue with command IDs and overlapping load classes - that might become an eyesore. Perhaps `LoadCommand.create(:LC_WHATEVER, ...)`? That might further enforce the point that load commands created this way are less complete than those created directly by `new`/`new_from_bin`.

> To be honest I don't have an idea yet that satisfies me truly.

Yeah, me neither :smile:. The `IsolatedCommandExtension` idea was just a random one - I'm not convinced it's the best (or even a good) approach.

I'll give these options some thought and see what I can come up with.

**Comment by UniqMartin** [comment]
> Perhaps `LoadCommand.create(:LC_WHATEVER, ...)`? That might further enforce the point that load commands created this way are less complete than those created directly by `new`/`new_from_bin`.

It's funny how you come up with an idea that was also floating around in my head but that I decided not to write down in my previous comment. 😄 Not sure if this is the best idea, but probably worth exploring. I guess it would be used something like this:

```ruby
rpath = LoadCommand.create(:LC_RPATH,
  :path => path)

id_dylib = LoadCommand.create(:LC_ID_DYLIB,
  :name => name,
  :timestamp => timestamp,
  :current_version => current_version,
  :compatibility_version => compatibility_version)
```

Or what was your plan for the `...`? :wink:

> I'll give these options some thought and see what I can come up with.

:+1:

**Comment by woodruffw** [comment]
> Or what was your plan for the ...?

Yep, that looks similar to what what I had in mind :smile:

**Comment by woodruffw** [comment]
Hmm, we're going to have problems with the fact that the commands that we want to create (e.g. `LC_RPATH`) don't take arguments for things like strings directly - they calculate them from the data provided in the `view`.

I'm going to push a (very hacky and experimental) branch in a few hours that implements the `LoadCommand.create` approach, but I'm not sure that it's going to be the best one for our needs.

**Comment by woodruffw** [comment]
Another idea:

Since the current implementation of load commands in `ruby-macho` is tightly bound to a source of Mach-O data, perhaps it makes sense to isolate creatable analogues to the `LoadCommand` classes in a `MachO::Creatable` namespace? We could then have creatables for individual signatures of load commands (e.g. `CreatableIdDylib`, `CreatableLoadDylib`) to avoid the messiness of having the user pass in a symbol (and sorting out the correct arguments).

This could be made to operate with the existing `LoadCommand` hierarchy through a conversion method, perhaps `LoadCommand#creatable_instance` or `LoadCommand#mutable_instance` that would return the appropriate instance.

**Comment by UniqMartin** [comment]
I've pondered this a little bit and I think at this stage we should be focusing on getting to a state where we can instantiate `DylibCommand` and `RpathCommand` out of thin air (`LoadCommand#@view` remains unset) or clone them from an existing instance (thereby also disassociating them from the Mach-O file/view it is linked to). I believe this can be achieved with minimal changes like the following:

```diff
diff --git i/lib/macho/load_commands.rb w/lib/macho/load_commands.rb
index 5a7c87d0..4a2f8c3c 100644
--- i/lib/macho/load_commands.rb
+++ w/lib/macho/load_commands.rb
@@ -209,10 +209,15 @@ module MachO
       # @api private
       def initialize(lc, lc_str)
         view = lc.view
-        lc_str_abs = view.offset + lc_str
-        lc_end = view.offset + lc.cmdsize - 1
-        @string = view.raw_data.slice(lc_str_abs..lc_end).delete("\x00")
-        @string_offset = lc_str
+        if view
+          lc_str_abs = view.offset + lc_str
+          lc_end = view.offset + lc.cmdsize - 1
+          @string = view.raw_data.slice(lc_str_abs..lc_end).delete("\x00")
+          @string_offset = lc_str
+        else
+          @string = lc_str
+          @string_offset = nil
+        end
       end

       # @return [String] a string representation of the LCStr
```

This should already cover the “instantiate out of thin air” case, i.e. `@view` and the `@string_offset` of any contained `LCStr` remain unset. This might not be the ideal solution, but I think we'll get pretty far with this approach (including serializing those back to a byte stream for replacement or addition of load commands when adding/changing/removing the relevant load commands).

I think that once we have this working, we'll have a much better understanding of what information we need when and how we might restructure all of the load command handling to be cleaner. But it feels like we're not ready for this refactoring yet and it can wait a bit longer. What are your thoughts?

**Comment by UniqMartin** [comment]
Yes, I agree that the different interpretation of the `lc_str` argument (respectively `name` and `path` if seen from the point of view of the hosting load command) depending on whether `view` is `nil` or not isn't entirely satisfying. I'm sure we can do better, but I think it's a reasonable compromise to get the task done efficiently and to gain some experience. It's not meant as a permanent solution and I'd suggest to use `@todo` in the relevant documentation comments to avoid forgetting this.

**Comment by woodruffw** [comment]
> I'd suggest to use @todo in the relevant documentation comments to avoid forgetting this.

Added, thanks for reminding me!

**Comment by UniqMartin** [comment]
With #38 merged I guess this could be considered resolved, right?
