### ISSUE TITLE
MachO::Sections function flag? implementation is wrong

### ISSUE THREAD

**Issue by iOS-Developer-Sun** [Homebrew/ruby-macho#423]
The SECTION_TYPE 0xff should be considered like

`flags & SECTION_TYPE ==  flag`

**Comment by woodruffw** [comment]
Thanks for catching that. I'll make a fix PR in a moment.

**Comment by woodruffw** [comment]
Oh, I think I see why this is -- we don't currently distinguish between the `SECTION_TYPE` masked area and the `SECTION_ATTRIBUTES` masked area within `flags`. Those should really be separate predicates, like `type?` and `attribute?`.

**Comment by woodruffw** [comment]
#424 will address this. It'll also do the same for segments, since `SegmentCommand#flag?` suffers from the same bug.

**Comment by iOS-Developer-Sun** [comment]
`flag?` is used in function `low_fileoff`
`next if sect.flag?(:S_ZEROFILL)
next if sect.flag?(:S_THREAD_LOCAL_ZEROFILL)`
It is not right although most of the time it returns the right section since the flags of the first section like `__text`, `__got` are usually even number. I think these two call references should be changed to `type?(:S_ZEROFILL)`. `flags?` is meaningless.

**Comment by woodruffw** [comment]
Yep, that's on the list of callsites to update. And yeah, I've marked `flags?` as deprecated and it'll be removed in an upcoming major release.
