### ISSUE TITLE
LCStr: Incorrect handling of null-terminated strings

### ISSUE THREAD

**Issue by UniqMartin** [Homebrew/ruby-macho#52]
The `alot` issue has also revealed another interesting, though completely unrelated, issue. Here's what I did with the `alot-python` binary (can provide it in full if it helps) after copying it from `Cellar/alot/0.3.7/libexec/bin/python`:

```console
$ ruby -Ilib -rmacho -e 'puts MachO::Tools.dylibs("alot-python").sort' > dylibs-rb.log
$ otool -L alot-python | tail -n +2 | awk '{print $1}' | sort > dylibs-cc.log
```

The resulting diff:

```diff
diff --git 1/dylibs-cc.log 2/dylibs-rb.log
index 6286cda5..a0b685cc 100644
--- 1/dylibs-cc.log
+++ 2/dylibs-rb.log
@@ -1,3 +1,3 @@
 /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 /usr/lib/libSystem.B.dylib
-@executable_path/../.Python
+@executable_path/../.Pythonython.framework/Versions/2.7/Python
```

The relevant section from the Mach-O file (the problematic load command starts at 0x13dc):

```console
$ hexdump -vC alot-python
[…snip…]
000013c0  00 5e 00 00 28 00 00 80  18 00 00 00 07 0e 00 00  |.^..(...........|
000013d0  00 00 00 00 00 00 00 00  00 00 00 00 0c 00 00 00  |................|
000013e0  58 00 00 00 18 00 00 00  02 00 00 00 0a 07 02 00  |X...............|
000013f0  00 07 02 00 40 65 78 65  63 75 74 61 62 6c 65 5f  |....@executable_|
00001400  70 61 74 68 2f 2e 2e 2f  2e 50 79 74 68 6f 6e 00  |path/../.Python.|
00001410  79 74 68 6f 6e 2e 66 72  61 6d 65 77 6f 72 6b 2f  |ython.framework/|
00001420  56 65 72 73 69 6f 6e 73  2f 32 2e 37 2f 50 79 74  |Versions/2.7/Pyt|
00001430  68 6f 6e 00 0c 00 00 00  34 00 00 00 18 00 00 00  |hon.....4.......|
00001440  02 00 00 00 01 0a ca 04  00 00 01 00 2f 75 73 72  |............/usr|
00001450  2f 6c 69 62 2f 6c 69 62  53 79 73 74 65 6d 2e 42  |/lib/libSystem.B|
00001460  2e 64 79 6c 69 62 00 00  0c 00 00 00 68 00 00 00  |.dylib......h...|
00001470  18 00 00 00 02 00 00 00  00 0c e8 04 00 00 96 00  |................|
[…snip…]
```

The issue is a mix of `LCStr` improperly extracting the string from the binary and `virtualenv` doing really ugly and naive things in its [`mach_o_change` function](https://github.com/pypa/virtualenv/blob/4b707b87d43e7e0a945ad831e6ce483b45440149/virtualenv.py#L2272-L2328). We can't really do anything about `virtualenv`, but `LCStr` should really only fetch the null-terminated string at the given offset and not assume that the rest of the load command is zero-padded.

cc @woodruffw

**Comment by woodruffw** [comment]
Ugh, that is not good behavior on either side. We should also definitely report this upstream - their code *works*, but it's certainly not ideal or in line with `libmacho`.

Good catch, I'll have a PR in a few minutes :+1:

**Comment by UniqMartin** [comment]
> We should also definitely report this upstream - their code *works*, but it's certainly not ideal or in line with `libmacho`.

I agree. I guess they picked the path of least resistance, and that works out nicely if they can guarantee the new name will never be longer than the old name. Apple's tools don't seem to mind, including the dynamic linker. I'm wondering why they didn't use `install_name_tool` for the job as they seem to have a dependency on a complete toolchain anyway.

(But then again I'm not a Python guru. In fact I'm actually quite clueless about :snake:. :joy:)

**Comment by woodruffw** [comment]
Yeah, the blame definitely rests more on `ruby-macho` than on `virtualenv` - the Mach-O spec says nothing about what load commands are padded *with*.

I'll open an issue on `virtualenv` tonight or tomorrow - it probably won't require a fix on their end, but they might want to know anyway.


> (But then again I'm not a Python guru. In fact I'm actually quite clueless about :snake:. :joy:)

I know just enough Python to know that I prefer Ruby :wink:
