### ISSUE TITLE
Expand binaries in test suite.

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#6]
The current test suite binaries do not contain load commands like `LC_LOAD_UPWARD_DYLIB` and `LC_LAZY_LOAD_DYLIB` (#3). These need to be added to improve coverage.

Goals:
- [x]  Add `LC_LOAD_UPWARD_DYLIB` binary and tests.
- [ ]  Add `LC_LAZY_LOAD_DYLIB` binary and tests.

**Comment by woodruffw** [comment]
Pinging @UniqMartin:

I'm having some trouble producing binaries with `LC_LAZY_LOAD_DYLIB` commands in them. Neither `-lazy_library` and `-lazy_l<whatever>` produces any warnings or errors, but their specified library isn't included in the product dylib.

I don't see an immediate explanation in the [source of `ld64`](http://www.opensource.apple.com/source/ld64/ld64-253.3/src/ld/InputFiles.cpp):
```C++
if ( info.options.fLazyLoad )
	reader->setWillBeLazyLoadedDylb();
```

Do you have any thoughts/knowledge of the linker's internal works here?

On a more positive note, I have had some success with `LC_LOAD_UPWARD_DYLIB`. I'll be adding those files and respective tests shortly.

**Comment by UniqMartin** [comment]
> I'm having some trouble producing binaries with `LC_LAZY_LOAD_DYLIB` commands in them.

[Here's a gist](https://gist.github.com/UniqMartin/e67e9b5dfe605fcc2090) with a minimal example that works for me. Just invoke `make` to produce a library and two binaries: `hi` links normally to `libhello.dylib` while `hi-lazy` does so lazily. You can observe the different behavior at run-time if you set `DYLD_PRINT_LIBRARIES=1` in the environment and then invoke both binaries first with and then without arguments.

**Comment by woodruffw** [comment]
I've gotten it to work by lazy-linking to another dylib that I generate. It doesn't seem to like lazy-linking to system dylibs, very strange.

I'll have the updated tests and dylibs committed in a bit.

**Comment by UniqMartin** [comment]
> It doesn't seem to like lazy-linking to system dylibs, very strange.

I think the problem why this didn't work is the specific libraries you picked: `/usr/lib/libpthread.dylib` has a dylib ID of `/usr/lib/libSystem.B.dylib` and so does `/usr/lib/libm.dylib` that you also tried to link to in the same example. (I think they only exist under these different names to accommodate for UNIX/Linux software, but in OS X that's all in one library.) Thus from the linker's perspective it's the same library, so the second load command might have been optimized away.

**Comment by woodruffw** [comment]
> I think the problem why this didn't work is the specific libraries you picked: /usr/lib/libpthread.dylib has a dylib ID of /usr/lib/libSystem.B.dylib and so does /usr/lib/libm.dylib that you also tried to link to in the same example. (I think they only exist under these different names to accommodate for UNIX/Linux software, but in OS X that's all in one library.) Thus from the linker's perspective it's the same library, so the second load command might have been optimized away.

Yep, I just checked - they're the same file. That was silly of me.
