### ISSUE TITLE
Expanding Makefile/build system to create inconsistent fat binaries

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#60]
I'm currently looking at the [Makefile](https://github.com/Homebrew/ruby-macho/blob/master/test/src/Makefile) to see what our best approach is to creating inconsistent fat binaries (i.e., the kind that will trigger the new behavior in #55).

In order to `lipo` together two inconsistent binaries of different architectures, we need a fat-only target that can generically depend on two single-arch-only targets. That's not possible with the current layout of the `Makefile`, and probably won't be without some significant changes.

For the time being, it might be worthwhile to externalize this process to a shell script, one that's called by the makefile at the very end of the `all:` chain. With a few minor tweaks, I can provide that script with the information it needs to access the correct single-arch directories and drop the `lipo`'d results in the correct fat-arch directories.

cc @UniqMartin

**Comment by woodruffw** [comment]
The closest I've come is doing some voodoo with `filter-out` and splitting `ALL_DIRS` into `SINGLE_DIRS` and `FAT_DIRS` and adding special fat-only targets, but this hasn't led me anywhere meaningful.

(I think the easiest approach is just to use the `libhello.dylib` from one arch and the `libextrahello.dylib` from another, since we already guarantee that `libextrahello.dylib` has additional dylib load commands that `libhello.dylib` cannot have.)

**Comment by woodruffw** [comment]
https://github.com/Homebrew/ruby-macho/commit/a34fed9b994046f75bb3115358aa8a69b7e81f66 on [ruby-macho/inconsistent-dylib-tests](https://github.com/Homebrew/ruby-macho/tree/inconsistent-dylib-tests) shows what I had in mind re: an external script called by the Makefile.

**Comment by UniqMartin** [comment]
I'm pretty sure this can be done with a `Makefile` but I'm perfectly happy with the solution you came up with. This can always be cleaned up and optimized later, and the shell script gets the job done nicely and allows us to move forward. :+1: Closing in favor of #61.
