### ISSUE TITLE
Mergable Libraries are unsupported

### ISSUE THREAD

**Issue by abarisain** [Homebrew/ruby-macho#609]
Hello!

Apple has introduced [mergable libraries](https://developer.apple.com/videos/play/wwdc2023/10268/) with Xcode 15.

As I understand them, they are dynamic frameworks but come with additional metadata allowing them to be statically merged.

It also comes with a new load command, `LC_ATOM_INFO` (code 0x36) https://github.com/llvm/llvm-project/blob/82c5d350d200ccc5365d40eac187b9ec967af727/llvm/include/llvm/BinaryFormat/MachO.def#L80 

This library doesn't understand this code and fails parsing the binary.
I'm not sure what you could to with it or what you could expose, I just thought I'd let you know as it breaks parsing altogether.

Have a nice day,
Arnaud

PS: I noticed this issue via CocoaPods, which still uses version 2.5 of this library. So, I don't think there's a need to rush this.

**Comment by woodruffw** [comment]
Thanks for reporting this @abarisain! We've merged the fix, and I can do a release if it'd help. But yeah, CocoaPods should probably upgrade first 🙂

**Comment by abarisain** [comment]
Thank you for the fast fix!

I don't think there is any rush to cut a release.

**Comment by goncg007** [comment]
Doesn't Cocoapods need a release of Macho to fix the problem there?

**Comment by goncg007** [comment]
@woodruffw is it possible to release a version with this fix?

**Comment by goncg007** [comment]
yes please @woodruffw, and then I can create a PR in Cocoapods to update them and use your newest version. 
Let me know when the version is out please.

**Comment by abarisain** [comment]
Please ease up on the maintainer pressure here, we had literally 0 signal from cocoapods that they intend to update this library or merge your PR anytime soon. 

Those things take time :)

**Comment by MikeMcQuaid** [comment]
@goncg007 Would suggest the PR is opened first using a non-tagged version of this library to check that Cocoapods are willing to do this and it doesn't break anything on their end. Once Cocoapods are 👍🏻 and @woodruffw is ready: it could be tagged.

**Comment by Bo98** [comment]
This is released in 4.1.0, which we made for macOS 15 support. I don't think this changes the situation much here as there's no movement downstream, but everything's done from our side anyway.
