### ISSUE TITLE
New DSL for MachOStructure

### ISSUE THREAD

**Issue by woodruffw** [Homebrew/ruby-macho#70]
This is just for collecting my thoughts and getting feedback on a DSL for `MachOStructure` (and, by inheritance, just about every Mach-O data-oriented class in `ruby-macho`.

The current "DSL" for a Mach-O structure looks something like this: 

```ruby
class SomeImportantStruct < MachOStructure
  attr_reader :something
  attr_reader :something_else

  FORMAT = "L=2" # something and something_else are "L", meaning int32s
  SIZEOF = 8 # 2 x sizeof(int32)

  def initialize(something, something_else)
    # ...
  end 
end
```

This is incredibly repetitive, bug-prone, and difficult to read (there's no immediate way to determine the size of each field).

Something like this would be *substantially* better:

```ruby
class SomeImportantStruct < MachOStructure
  field :int32, :something
  field :int32, :something_else

  # FORMAT, SIZEOF, and instantiation are automatically generated from the field definitions
end
```

Extremely early versions of `ruby-macho` actually had something like this, using `CStruct` [from this repo](https://github.com/samsonjs/compiler), but I dropped it for reasons that I don't remember (probably having to do with me being unfamiliar with ruby DSL writing at the time).

This will probably require a large amount of refactoring and breakage, so I don't think it'll make it into 1.1 (or even 1.x, it might be destined for a major bump).

**Comment by aidansteele** [comment]
Are you familiar with the [`bindata`](https://github.com/dmendel/bindata) gem? It sounds like exactly what you're after. I've used it to great success with projects very similar to this gem.

**Comment by woodruffw** [comment]
@aidansteele That looks like exactly what I want, thank you!

**Comment by aidansteele** [comment]
No worries 👍 While I'm thinking of it, there's also this repo I put up a while ago:

https://github.com/aidansteele/osx-abi-macho-file-format-reference

It's just a markdown version (+ original Apple PDF) of the _OS X ABI Mach-O File Format Reference_. This document used to be on Apple's website until relatively recently, but seems to have dropped off the face of the Earth. Which is a shame, because it's probably the most useful reference document I can think of for this project.

**Comment by woodruffw** [comment]
> This document used to be on Apple's website until relatively recently, but seems to have dropped off the face of the Earth.

Yep, I know exactly what you're talking about. That reference + the `cctools` source basically made ruby-macho possible. Thank you so much for archiving it!

**Comment by luikore** [comment]
I think an API like construct is super concise and expressive, much better than bindata

You can see how simple it is to parse macho and code signature in python:

https://github.com/comex/cs/blob/master/macho.py
https://github.com/comex/cs/blob/master/macho_cs.py

**Comment by apainintheneck** [comment]
I'd be interested in working on this. I assume the main thing is just to generate the sizeof, format and initialize() portions of the class. I'm pretty new to Ruby dsl design but I'll see what I can code up.

**Comment by apainintheneck** [comment]
I was thinking about something like the following which would replace the attr_reader, format, sizeof, and initialize parts of the current class definition.

```Ruby
class SomeImportantStruct < MachOStructure
  field :something, :uint32
  # Strings also need custom size
  field :something_else, :string, :size => len
  # Occasionally a custom bitmask is used
  field :another_one, :int32, :mask => bitmask
  # Finally custom types are sometimes necessary
  field :one_more, :custom, :size => len, :fmt => format_string
end
```

**Comment by woodruffw** [comment]
Something like that looks reasonable to me.

For `:string`, we can probably do something like `:string => :lcstr` to
indicate that the string should be parsed as a `struct lc_str`, since that's
the most common (only?) case.

**Comment by apainintheneck** [comment]
Oh yeah, I hadn't gotten around to thinking about the fields that don't actually add anything to the format or sizeof attributes. The :string I was talking about above was the null terminated string that parses with the letter Z that's used in the Section classes. 

After a quick look around it seems like the main ones I was missing were the lc_str and view attributes that are added to a few classes. I'm almost inclined to just make those their own types.

```Ruby
class SomeImportantStruct < MachOStructure
  field :name1, :view
  field :name2, :lcstr
end
```
